version: "3.4"

services:
  web:
    image: docker.pkg.github.com/chrisvrose/couscous-next
    ports:
      - 8081:3000
    environment:
      - MYSQL_DATABASE=couscous
      - MYSQL_USER=couscous
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysqldb
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - MONGOSDB_HOST=mongosdb
    links:
      - mysqldb
      - mongosdb
    depends_on:
      - mysqldb
      - mongosdb
  mysqldb:
    image: mysql
    hostname: mysqldb
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysqldata:/var/lib/mysql
      - ./misc/dbinit:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=couscous
      - MYSQL_USER=couscous
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  mongocfg:
    container_name: mongocfg
    hostname: mongocfg
    image: mongo
    command: --configsvr --replSet mongocfg --dbpath /data/db --port 27017 --bind_ip_all
    expose:
      - "27017"
    ports:
      - 27018:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongocfg
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongocfgdata:/data/db
  mongosdb:
    container_name: mongosdb
    hostname: mongosdb
    image: mongo
    entrypoint: mongos --configdb mongocfg/mongocfg:27017 --port 27017 --bind_ip_all
    depends_on:
      - mongocfg
    links:
      - mongocfg
    expose:
      - "27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongosdb
    volumes:
      - ./misc/mongocfginit/:/docker-entrypoint-initdb.d:ro
      - /etc/localtime:/etc/localtime:ro
      - mongosdata:/etc/mongos
    ports:
      - 27017:27017

volumes:
  mysqldata:
  mongosdata:
  mongocfgdata:
