# This is a 2 shard system
version: "3"

services:
  mongosh1:
    container_name: mongosh1
    image: mongo
    command: --shardsvr --replSet mongosh1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    environment:
      - REPLSETNAME=mongosh1
    healthcheck:
      test: test $$(echo "rs.initiate({_id:\"mongosh1\",members:[{_id:0,host:\"mongosh1\"}]}).ok || rs.status().ok" | mongo  --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongos1:/data/db
  mongosh2:
    container_name: mongosh2
    image: mongo
    command: --shardsvr --replSet mongosh2  --dbpath /data/db --port 27017
    ports:
      - 27028:27017
    environment:
      - REPLSETNAME=mongosh2
    expose:
      - "27017"
    healthcheck:
      test: test $$(echo "rs.initiate({_id:\"mongosh2\",members:[{_id:0,host:\"mongosh2\"}]}).ok || rs.status().ok" | mongo  --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongos2:/data/db

volumes:
  mongos1:
  mongos2:
